// This file is generated by FBC.

#ifndef GLOBAL_H_
#define GLOBAL_H_


double x_u;

//Continous variable init

double x_init;

//The constant variable

double C1x;

//Step-size constant d
static double d=0.2;

//Nstep constant k

double k;

//States

enum states {t1 , t2 , t3 , t4};

//Previous state variable


static enum states pstate = -1;
static enum states cstate = t4;


#endif//GLOBAL_H_
